adding badge component
bipin7yadav/Component-library-project pull request #4
Opened 2022-02-06 18:40 UTC by bipin7yadav

2022-02-07 15:53 UTC, manojkumar8400 commented on badge.css
> +} */
suggestion -: Remove unused comments.

2022-02-07 15:53 UTC, manojkumar8400 approved these changes

2022-02-08 04:48 UTC, mimansha-swarup requested changes
remove unnecessary comments
use variable for colors
use consistent unit

2022-02-08 04:48 UTC, mimansha-swarup commented on badge.css
> +    background-color: rgb(155, 173, 238);
use variable

2022-02-08 04:48 UTC, mimansha-swarup commented on badge.css
> +    margin: 5px;
use consistent unit somewhere u are using px somewhere rem
i will suggest to stick with rem

2022-02-08 04:48 UTC, mimansha-swarup commented on badge.css
> +    /* z-index: 1; */
remove unnecessary comments

2022-02-08 04:48 UTC, mimansha-swarup commented on badge.css
> +    margin-left: -3rem;
i guess margin-left is not necessary you can use left instead depends on your use-case too

2022-02-08 17:02 UTC, merged